<a href="https://colab.research.google.com/github/hariprasathys22/Pytorch_project_1/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
#reshape if we dont know the of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
my_torch5 = my_torch3.reshape(2,5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
my_torch3[1] = 4141
my_torch3

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [17]:
my_torch5

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [19]:
#slice
my_torch6 = torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_torch6[7]

tensor(7)

In [24]:
my_torch7 = my_torch6.reshape(5,2)
my_torch7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

# Tensor Math Operation
## Add, Substract, multiply, divide, remainders, exponents

In [25]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [26]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [27]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [28]:
tensor_b - tensor_a


tensor([4, 4, 4, 4])

In [29]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [30]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [31]:
torch.mul(tensor_a, tensor_b)


tensor([ 5, 12, 21, 32])

In [32]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [33]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [34]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [36]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [37]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [39]:
#reassignment the addition value to target tensor
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [40]:
tensor_a

tensor([ 6,  8, 10, 12])